apiVersion: v1
kind: Secret
metadata:
  name: portal-secrets
  namespace: portal
type: Opaque
stringData:
  PORTAL_MONGO_URI: mongodb://mongo.portal.svc.cluster.local:27017
  KEYCLOAK_CLIENT_SECRET: change-me
  KEYCLOAK_ADMIN_CLIENT_SECRET: change-me
  KEYCLOAK_ADMIN_USERNAME: admin
  KEYCLOAK_ADMIN_PASSWORD: admin123
